-- functions and procedures to support historical retrieval of FSA file
--
--  Function LATEST_FSA()
--		returns most recent version of FSA
--		ex: SELECT * FROM TABLE(LATEST_FSA())
--
--  Function LATEST_FSA(MAX_DATE)
--		returns the version of FSA table AT or BEFORE the given MAX_DATE
--		ex: SELECT * FROM TABLE(LATEST_FSA('2023-04-25 23:59'::timestamp_ltz))
--
--  Function LATEST_FSA_CONSOLIDATED()
--		returns most recent version of FSA table through the view FSA_CONSOLIDATED
--		ex: SELECT * FROM TABLE(LATEST_FSA_CONSOLIDATED())
--
--  Function LATEST_FSA_CONSOLIDATED(MAX_DATE)
--		returns the version of FSA_CONSOLIDATED view AT or BEFORE the given MAX_DATE
--		ex: SELECT * FROM TABLE(LATEST_FSA_CONSOLIDATED('2023-04-25 23:59'::timestamp_ltz))
--
--  Procedure MAKE_FSA()
--		Creates FSA table from the most recent version, named FSA
--		ex: CALL MAKE_FSA()
--
--  Procedure MAKE_FSA(MAX_DATE)
--		Creates FSA table from the version AT or BEFORE the given MAX_DATE, named FSA
--		ex: CALL MAKE_FSA('2023-04-25 23:59')
--		ex: CALL MAKE_FSA('2023-04-26') 		-- same as previous (within a minute anyway)
--
--  Procedure MAKE_FSA(MAX_DATE,TARGET_TABLE)
--		Creates FSA table from the version AT or BEFORE the given MAX_DATE, named TARGET_TABLE
--		ex: CALL MAKE_FSA('2023-04-25 23:59','TEST_FSA')
--


CREATE OR REPLACE FUNCTION DEV.${FSA_PROD_SCHEMA}.LATEST_FSA (MAX_DATE timestamp_ltz)
  RETURNS TABLE (
	PO_ID NUMBER(23,5),
	FSA_LOAD_STATUS VARCHAR(16777216),
	ID NUMBER(18,0),
	ITEM_ID NUMBER,
	ORIGINAL_DDA DATE,
	SEQUENCING_DDA DATE,
	ORDER_NUMBER VARCHAR(360),
	TOTAL_AVAIL_QTY NUMBER,
	QUANTITY NUMBER,
	REMAINING_AVAIL_QTY NUMBER,
	SUM_ROLLUP NUMBER,
	PRELIM_EDD DATE,
	ITEM VARCHAR(4400),
	LOCATION VARCHAR(480),
	NS_LINE_NUMBER VARCHAR(16777216),
	ROW_NO NUMBER(38,0),
	PRIORITY NUMBER(38,0),
	SEQ NUMBER(38,0),
	TRANSACTION_TYPE VARCHAR(16777216),
	TYPE_NAME VARCHAR(480),
	TRANSACTION_ID VARCHAR(16777216),
	LINE_ID VARCHAR(16777216),
	UNIQUE_KEY NUMBER,
	PO_SLIPPAGE BOOLEAN,
	ITEM_ROW_NO NUMBER(18,0),
	SOURCE_TYPE VARCHAR(8),
	COMPONENT_ITEM VARCHAR(4400),
	COMPONENT_ITEM_ID NUMBER(38,0),
	ITEM_ID_BY_TRANSACTION_TYPE NUMBER,
	SOURCE_LOAD_DATE TIMESTAMP_LTZ(9),
	PK_ID VARCHAR(16777216),
	IS_ASSEMBLY_COMPONENT BOOLEAN,
	CREATE_DATE TIMESTAMP_TZ(9),
	PO_INDICATOR NUMBER,
	PO_UPDATE_DATETIME VARCHAR(16777216),
	PO_ORDER_NUMBER VARCHAR(16777216),
	PO_QUANTITY_REMAINING NUMBER,
	PO_RECEIVE_BY_DATE DATE,
	PO_INDICATOR_ASSIGN NUMBER(1,0),
	PO_TOTAL_QUANTITY_TO_BE_RECEIVED NUMBER,
	SHARED_ORDER_NUMBER VARCHAR(16777216),
	FR_PREV_DAYS NUMBER,
	BOB_ORDER_NUMBER VARCHAR(360),
	AVAIL_DATE DATE,
	BOB_ITEM VARCHAR(4400),
	FREDD DATE,
	BUCKET_ON_AVAIL_DATE VARCHAR(16777216),
	BUCKET_DATE_ON_AVAIL_DATE DATE,
	IS_GT_15_BIZDAYS BOOLEAN,
	IF_BUCKET1 DATE,
	IF_BUCKET2 DATE,
	IF_BUCKET3 DATE,
	IF_BUCKET4 DATE,
	IF_BUCKET5 DATE,
	IF_BUCKET6 DATE,
	IF_BUCKET7 DATE,
	IF_BUCKET8 DATE,
	IF_BUCKET9 DATE,
	IF_BUCKET10 DATE,
	IF_BUCKET11 DATE,
	IF_BUCKET12 DATE,
	IF_BUCKET13 DATE,
	IF_BUCKET14 DATE,
	FSA_UPDATED_ORIGINAL_DDA DATE,
	ITEM_AVAIL_DATE DATE,
	FSA_OUTPUT_STATUS VARCHAR(16777216),
	CAPPING_DDA DATE,
	ORIG_CAP_DDA DATE,
	NEW_AVAIL_DATE DATE,
	PREV_AVAIL_DATE DATE,
	PREV_CAPPING_DDA DATE,
	PREV_PO_INDICATOR NUMBER(38,0),
	PREV_PO_INDICATOR_ASSIGN NUMBER(38,0),
	PREV_PO_ORDER_NUMBER VARCHAR(16777216),
	PREV_PO_RECEIVE_BY_DATE DATE) AS
$$
    select t1.* exclude (fsa_insert_date,is_valid)
      from dev.${FSA_PROD_SCHEMA}.fsa_historical t1
      join (
        select distinct source_load_date,max(fsa_insert_date) over () fsa_insert_date
        from dev.${FSA_PROD_SCHEMA}.fsa_historical
        where is_valid 
          and source_load_date = 
          (select max(source_load_date) source_load_date
            from dev.${FSA_PROD_SCHEMA}.fsa_historical
            where is_valid and source_load_date <= MAX_DATE)) t2
      on t1.source_load_date = t2.source_load_date
        and t1.fsa_insert_date = t2.fsa_insert_date
$$;

CREATE OR REPLACE FUNCTION DEV.${FSA_PROD_SCHEMA}.LATEST_FSA ()
  RETURNS TABLE (
	PO_ID NUMBER(23,5),
	FSA_LOAD_STATUS VARCHAR(16777216),
	ID NUMBER(18,0),
	ITEM_ID NUMBER,
	ORIGINAL_DDA DATE,
	SEQUENCING_DDA DATE,
	ORDER_NUMBER VARCHAR(360),
	TOTAL_AVAIL_QTY NUMBER,
	QUANTITY NUMBER,
	REMAINING_AVAIL_QTY NUMBER,
	SUM_ROLLUP NUMBER,
	PRELIM_EDD DATE,
	ITEM VARCHAR(4400),
	LOCATION VARCHAR(480),
	NS_LINE_NUMBER VARCHAR(16777216),
	ROW_NO NUMBER(38,0),
	PRIORITY NUMBER(38,0),
	SEQ NUMBER(38,0),
	TRANSACTION_TYPE VARCHAR(16777216),
	TYPE_NAME VARCHAR(480),
	TRANSACTION_ID VARCHAR(16777216),
	LINE_ID VARCHAR(16777216),
	UNIQUE_KEY NUMBER,
	PO_SLIPPAGE BOOLEAN,
	ITEM_ROW_NO NUMBER(18,0),
	SOURCE_TYPE VARCHAR(8),
	COMPONENT_ITEM VARCHAR(4400),
	COMPONENT_ITEM_ID NUMBER(38,0),
	ITEM_ID_BY_TRANSACTION_TYPE NUMBER,
	SOURCE_LOAD_DATE TIMESTAMP_LTZ(9),
	PK_ID VARCHAR(16777216),
	IS_ASSEMBLY_COMPONENT BOOLEAN,
	CREATE_DATE TIMESTAMP_TZ(9),
	PO_INDICATOR NUMBER,
	PO_UPDATE_DATETIME VARCHAR(16777216),
	PO_ORDER_NUMBER VARCHAR(16777216),
	PO_QUANTITY_REMAINING NUMBER,
	PO_RECEIVE_BY_DATE DATE,
	PO_INDICATOR_ASSIGN NUMBER(1,0),
	PO_TOTAL_QUANTITY_TO_BE_RECEIVED NUMBER,
	SHARED_ORDER_NUMBER VARCHAR(16777216),
	FR_PREV_DAYS NUMBER,
	BOB_ORDER_NUMBER VARCHAR(360),
	AVAIL_DATE DATE,
	BOB_ITEM VARCHAR(4400),
	FREDD DATE,
	BUCKET_ON_AVAIL_DATE VARCHAR(16777216),
	BUCKET_DATE_ON_AVAIL_DATE DATE,
	IS_GT_15_BIZDAYS BOOLEAN,
	IF_BUCKET1 DATE,
	IF_BUCKET2 DATE,
	IF_BUCKET3 DATE,
	IF_BUCKET4 DATE,
	IF_BUCKET5 DATE,
	IF_BUCKET6 DATE,
	IF_BUCKET7 DATE,
	IF_BUCKET8 DATE,
	IF_BUCKET9 DATE,
	IF_BUCKET10 DATE,
	IF_BUCKET11 DATE,
	IF_BUCKET12 DATE,
	IF_BUCKET13 DATE,
	IF_BUCKET14 DATE,
	FSA_UPDATED_ORIGINAL_DDA DATE,
	ITEM_AVAIL_DATE DATE,
	FSA_OUTPUT_STATUS VARCHAR(16777216),
	CAPPING_DDA DATE,
	ORIG_CAP_DDA DATE,
	NEW_AVAIL_DATE DATE,
	PREV_AVAIL_DATE DATE,
	PREV_CAPPING_DDA DATE,
	PREV_PO_INDICATOR NUMBER(38,0),
	PREV_PO_INDICATOR_ASSIGN NUMBER(38,0),
	PREV_PO_ORDER_NUMBER VARCHAR(16777216),
	PREV_PO_RECEIVE_BY_DATE DATE) AS
$$
	select * from TABLE(DEV.${FSA_PROD_SCHEMA}.LATEST_FSA(current_timestamp()))
$$;

CREATE OR REPLACE FUNCTION DEV.${FSA_PROD_SCHEMA}.LATEST_FSA (time_as_text text)
  RETURNS TABLE (
	PO_ID NUMBER(23,5),
	FSA_LOAD_STATUS VARCHAR(16777216),
	ID NUMBER(18,0),
	ITEM_ID NUMBER,
	ORIGINAL_DDA DATE,
	SEQUENCING_DDA DATE,
	ORDER_NUMBER VARCHAR(360),
	TOTAL_AVAIL_QTY NUMBER,
	QUANTITY NUMBER,
	REMAINING_AVAIL_QTY NUMBER,
	SUM_ROLLUP NUMBER,
	PRELIM_EDD DATE,
	ITEM VARCHAR(4400),
	LOCATION VARCHAR(480),
	NS_LINE_NUMBER VARCHAR(16777216),
	ROW_NO NUMBER(38,0),
	PRIORITY NUMBER(38,0),
	SEQ NUMBER(38,0),
	TRANSACTION_TYPE VARCHAR(16777216),
	TYPE_NAME VARCHAR(480),
	TRANSACTION_ID VARCHAR(16777216),
	LINE_ID VARCHAR(16777216),
	UNIQUE_KEY NUMBER,
	PO_SLIPPAGE BOOLEAN,
	ITEM_ROW_NO NUMBER(18,0),
	SOURCE_TYPE VARCHAR(8),
	COMPONENT_ITEM VARCHAR(4400),
	COMPONENT_ITEM_ID NUMBER(38,0),
	ITEM_ID_BY_TRANSACTION_TYPE NUMBER,
	SOURCE_LOAD_DATE TIMESTAMP_LTZ(9),
	PK_ID VARCHAR(16777216),
	IS_ASSEMBLY_COMPONENT BOOLEAN,
	CREATE_DATE TIMESTAMP_TZ(9),
	PO_INDICATOR NUMBER,
	PO_UPDATE_DATETIME VARCHAR(16777216),
	PO_ORDER_NUMBER VARCHAR(16777216),
	PO_QUANTITY_REMAINING NUMBER,
	PO_RECEIVE_BY_DATE DATE,
	PO_INDICATOR_ASSIGN NUMBER(1,0),
	PO_TOTAL_QUANTITY_TO_BE_RECEIVED NUMBER,
	SHARED_ORDER_NUMBER VARCHAR(16777216),
	FR_PREV_DAYS NUMBER,
	BOB_ORDER_NUMBER VARCHAR(360),
	AVAIL_DATE DATE,
	BOB_ITEM VARCHAR(4400),
	FREDD DATE,
	BUCKET_ON_AVAIL_DATE VARCHAR(16777216),
	BUCKET_DATE_ON_AVAIL_DATE DATE,
	IS_GT_15_BIZDAYS BOOLEAN,
	IF_BUCKET1 DATE,
	IF_BUCKET2 DATE,
	IF_BUCKET3 DATE,
	IF_BUCKET4 DATE,
	IF_BUCKET5 DATE,
	IF_BUCKET6 DATE,
	IF_BUCKET7 DATE,
	IF_BUCKET8 DATE,
	IF_BUCKET9 DATE,
	IF_BUCKET10 DATE,
	IF_BUCKET11 DATE,
	IF_BUCKET12 DATE,
	IF_BUCKET13 DATE,
	IF_BUCKET14 DATE,
	FSA_UPDATED_ORIGINAL_DDA DATE,
	ITEM_AVAIL_DATE DATE,
	FSA_OUTPUT_STATUS VARCHAR(16777216),
	CAPPING_DDA DATE,
	ORIG_CAP_DDA DATE,
	NEW_AVAIL_DATE DATE,
	PREV_AVAIL_DATE DATE,
	PREV_CAPPING_DDA DATE,
	PREV_PO_INDICATOR NUMBER(38,0),
	PREV_PO_INDICATOR_ASSIGN NUMBER(38,0),
	PREV_PO_ORDER_NUMBER VARCHAR(16777216),
	PREV_PO_RECEIVE_BY_DATE DATE) AS
$$
	select * from TABLE(DEV.${FSA_PROD_SCHEMA}.LATEST_FSA(try_to_timestamp_ltz(time_as_text)))
$$;

CREATE OR REPLACE FUNCTION DEV.${FSA_PROD_SCHEMA}.LATEST_FSA_CONSOLIDATED (MAX_DATE timestamp_ltz)
  RETURNS TABLE (
	ORDER_NUMBER VARCHAR(360),
	NS_LINE_NUMBER TEXT,
	TRANSACTION_ID TEXT,
	LINE_ID TEXT,
	FSA_OUTPUT_STATUS TEXT,
	CREATE_DATE TIMESTAMP_TZ,
	ROW_NO NUMBER,
	ORIGINAL_CAPPING_DDA DATE,
	FREDD DATE,
	CAPPING_DDA DATE
	) AS
$$
	SELECT ORDER_NUMBER
      ,NS_LINE_NUMBER
      ,TRANSACTION_ID
      ,LINE_ID
      ,FSA_OUTPUT_STATUS
      ,CREATE_DATE
      ,ROW_NO             AS "ROW_NO"
      ,ORIG_CAP_DDA       AS "ORIGINAL_CAPPING_DDA"
      ,MAX(FREDD)         AS "FREDD"
      ,MAX(CAPPING_DDA)   AS "CAPPING_DDA"
	FROM TABLE(DEV.${FSA_PROD_SCHEMA}.LATEST_FSA(MAX_DATE))
	WHERE SOURCE_TYPE = 'OpenSO'
	GROUP BY 1,2,3,4,5,6,7,8
$$;

CREATE OR REPLACE FUNCTION DEV.${FSA_PROD_SCHEMA}.LATEST_FSA_CONSOLIDATED()
  RETURNS TABLE (
	ORDER_NUMBER VARCHAR(360),
	NS_LINE_NUMBER TEXT,
	TRANSACTION_ID TEXT,
	LINE_ID TEXT,
	FSA_OUTPUT_STATUS TEXT,
	CREATE_DATE TIMESTAMP_TZ,
	ROW_NO NUMBER,
	ORIGINAL_CAPPING_DDA DATE,
	FREDD DATE,
	CAPPING_DDA DATE
	) AS
$$
	SELECT * FROM TABLE(DEV.${FSA_PROD_SCHEMA}.LATEST_FSA_CONSOLIDATED(current_timestamp()))
$$;

CREATE OR REPLACE PROCEDURE DEV.${FSA_PROD_SCHEMA}.MAKE_FSA(MAX_DATE timestamp_ltz,TARGET_TABLE text)
  RETURNS TABLE()
  LANGUAGE SQL
  EXECUTE AS CALLER
AS $$
  BEGIN
  LET rs RESULTSET := (CREATE OR REPLACE TABLE IDENTIFIER(:TARGET_TABLE) AS SELECT * FROM TABLE(DEV.${FSA_PROD_SCHEMA}.LATEST_FSA(:MAX_DATE)));
  return TABLE(rs);
  END;
$$;

CREATE OR REPLACE PROCEDURE DEV.${FSA_PROD_SCHEMA}.MAKE_FSA(MAX_DATE timestamp_ltz)
  RETURNS TABLE()
  LANGUAGE SQL
  EXECUTE AS CALLER
AS $$
  BEGIN
  LET rs RESULTSET := (CALL DEV.${FSA_PROD_SCHEMA}.MAKE_FSA(:MAX_DATE,'DEV.${FSA_PROD_SCHEMA}.FSA'));
  return TABLE(rs);
  END;
$$;

CREATE OR REPLACE PROCEDURE DEV.${FSA_PROD_SCHEMA}.MAKE_FSA()
  RETURNS TABLE()
  LANGUAGE SQL
  EXECUTE AS CALLER
AS $$
  BEGIN
  LET rs RESULTSET := (CALL DEV.${FSA_PROD_SCHEMA}.MAKE_FSA(current_timestamp()));
  return TABLE(rs);
  END;
$$;

CREATE OR REPLACE FUNCTION DEV.${FSA_PROD_SCHEMA}.DATES_FSA()
  RETURNS TABLE(
    RECENT_OR_INORDER NUMBER,
    SOURCE_LOAD_DATE TIMESTAMP_LTZ,
    FSA_INSERT_DATE TIMESTAMP_LTZ
  	) AS 
$$
  select * from
  (
    select row_number() over (order by source_load_date,fsa_insert_date)-1 rep_order,
            source_load_date,
            max(fsa_insert_date) over (partition by source_load_date) fsa_insert_date
        from DEV.${FSA_PROD_SCHEMA}.fsa_historical 
        where is_valid 
        group by source_load_date,fsa_insert_date
    union
    select row_number() over (order by source_load_date desc,fsa_insert_date)*-1 rep_order,
            source_load_date,
            max(fsa_insert_date) over (partition by source_load_date) fsa_insert_date
        from DEV.${FSA_PROD_SCHEMA}.fsa_historical 
        where is_valid 
        group by source_load_date,fsa_insert_date
  )
  order by rep_order
$$;

CREATE OR REPLACE FUNCTION DEV.${FSA_PROD_SCHEMA}.LATEST_FSA (recent_or_inorder NUMBER)
  RETURNS TABLE (
	PO_ID NUMBER(23,5),
	FSA_LOAD_STATUS VARCHAR(16777216),
	ID NUMBER(18,0),
	ITEM_ID NUMBER,
	ORIGINAL_DDA DATE,
	SEQUENCING_DDA DATE,
	ORDER_NUMBER VARCHAR(360),
	TOTAL_AVAIL_QTY NUMBER,
	QUANTITY NUMBER,
	REMAINING_AVAIL_QTY NUMBER,
	SUM_ROLLUP NUMBER,
	PRELIM_EDD DATE,
	ITEM VARCHAR(4400),
	LOCATION VARCHAR(480),
	NS_LINE_NUMBER VARCHAR(16777216),
	ROW_NO NUMBER(38,0),
	PRIORITY NUMBER(38,0),
	SEQ NUMBER(38,0),
	TRANSACTION_TYPE VARCHAR(16777216),
	TYPE_NAME VARCHAR(480),
	TRANSACTION_ID VARCHAR(16777216),
	LINE_ID VARCHAR(16777216),
	UNIQUE_KEY NUMBER,
	PO_SLIPPAGE BOOLEAN,
	ITEM_ROW_NO NUMBER(18,0),
	SOURCE_TYPE VARCHAR(8),
	COMPONENT_ITEM VARCHAR(4400),
	COMPONENT_ITEM_ID NUMBER(38,0),
	ITEM_ID_BY_TRANSACTION_TYPE NUMBER,
	SOURCE_LOAD_DATE TIMESTAMP_LTZ(9),
	PK_ID VARCHAR(16777216),
	IS_ASSEMBLY_COMPONENT BOOLEAN,
	CREATE_DATE TIMESTAMP_TZ(9),
	PO_INDICATOR NUMBER,
	PO_UPDATE_DATETIME VARCHAR(16777216),
	PO_ORDER_NUMBER VARCHAR(16777216),
	PO_QUANTITY_REMAINING NUMBER,
	PO_RECEIVE_BY_DATE DATE,
	PO_INDICATOR_ASSIGN NUMBER(1,0),
	PO_TOTAL_QUANTITY_TO_BE_RECEIVED NUMBER,
	SHARED_ORDER_NUMBER VARCHAR(16777216),
	FR_PREV_DAYS NUMBER,
	BOB_ORDER_NUMBER VARCHAR(360),
	AVAIL_DATE DATE,
	BOB_ITEM VARCHAR(4400),
	FREDD DATE,
	BUCKET_ON_AVAIL_DATE VARCHAR(16777216),
	BUCKET_DATE_ON_AVAIL_DATE DATE,
	IS_GT_15_BIZDAYS BOOLEAN,
	IF_BUCKET1 DATE,
	IF_BUCKET2 DATE,
	IF_BUCKET3 DATE,
	IF_BUCKET4 DATE,
	IF_BUCKET5 DATE,
	IF_BUCKET6 DATE,
	IF_BUCKET7 DATE,
	IF_BUCKET8 DATE,
	IF_BUCKET9 DATE,
	IF_BUCKET10 DATE,
	IF_BUCKET11 DATE,
	IF_BUCKET12 DATE,
	IF_BUCKET13 DATE,
	IF_BUCKET14 DATE,
	FSA_UPDATED_ORIGINAL_DDA DATE,
	ITEM_AVAIL_DATE DATE,
	FSA_OUTPUT_STATUS VARCHAR(16777216),
	CAPPING_DDA DATE,
	ORIG_CAP_DDA DATE,
	NEW_AVAIL_DATE DATE,
	PREV_AVAIL_DATE DATE,
	PREV_CAPPING_DDA DATE,
	PREV_PO_INDICATOR NUMBER(38,0),
	PREV_PO_INDICATOR_ASSIGN NUMBER(38,0),
	PREV_PO_ORDER_NUMBER VARCHAR(16777216),
	PREV_PO_RECEIVE_BY_DATE DATE) AS
$$
	select f.* exclude (fsa_insert_date,is_valid)
    from DEV.${FSA_PROD_SCHEMA}.FSA_HISTORICAL f
    join table(DEV.${FSA_PROD_SCHEMA}.DATES_FSA()) d
    	on f.source_load_date = d.source_load_date
           and f.fsa_insert_date = d.fsa_insert_date
    where f.is_valid
		and d.RECENT_OR_INORDER = recent_or_inorder
$$;

