-- functions and procedures to support historical retrieval of OPEN_PO_ALL file
--
--  Function LATEST_OPEN_PO_ALL()
--		returns most recent version of OPEN_PO_ALL
--		ex: SELECT * FROM TABLE(LATEST_OPEN_PO_ALL())
--
--  Function LATEST_OPEN_PO_ALL(MAX_DATE)
--		returns the version of OPEN_PO_ALL table AT or BEFORE the given MAX_DATE
--		ex: SELECT * FROM TABLE(LATEST_OPEN_PO_ALL('2023-04-25 23:59'::timestamp_ltz))
--
--  Procedure MAKE_OPEN_PO_ALL()
--		Creates OPEN_PO_ALL table from the most recent version, named OPEN_PO_ALL
--		ex: CALL MAKE_OPEN_PO_ALL()
--
--  Procedure MAKE_OPEN_PO_ALL(MAX_DATE)
--		Creates OPEN_PO_ALL table from the version AT or BEFORE the given MAX_DATE, named OPEN_PO_ALL
--		ex: CALL MAKE_OPEN_PO_ALL('2023-04-25 23:59')
--		ex: CALL MAKE_OPEN_PO_ALL('2023-04-26') 		-- same as previous (within a minute anyway)
--
--  Procedure MAKE_OPEN_PO_ALL(MAX_DATE,TARGET_TABLE)
--		Creates FOPEN_PO_ALLSA table from the version AT or BEFORE the given MAX_DATE, named TARGET_TABLE
--		ex: CALL MAKE_OPEN_PO_ALL('2023-04-25 23:59','TEST_OPEN_PO_ALL')
--

CREATE OR REPLACE FUNCTION DEV.${FSA_CURRENT_SCHEMA}.LATEST_OPEN_PO_ALL (MAX_DATE timestamp_ltz)
  RETURNS TABLE (
	PO_ROW_NO NUMBER(18,0),
	PO_ITEM_ID FLOAT,
	PO_ITEM_TYPE VARCHAR(11),
	ITEM_ID FLOAT,
	ITEM VARCHAR(4400),
	ITEM_ID_C NUMBER(38,0),
	ITEM_C VARCHAR(4400),
	ITEM_DISPLAY_NAME VARCHAR(2000),
	ASSEMBLY_ITEM_ID FLOAT,
	ASSEMBLY_ITEM VARCHAR(4400),
	ASSEMBLY_ITEM_DISPLAY_NAME VARCHAR(2000),
	ORDER_NUMBER VARCHAR(360),
	PURCHASE_ORDER_TRANSACTION_ID FLOAT,
	STATUS VARCHAR(32000),
	LOCATION VARCHAR(480),
	RECEIVE_BY_DATE DATE,
	NS_RECEIVE_BY_DATE DATE,
	UNIQUE_KEY FLOAT,
	QUANTITY_TO_BE_RECEIVED FLOAT,
	HASH_VALUE VARCHAR(16777216),
	FSA_LOAD_STATUS VARCHAR(16777216),
	INSERT_DATE TIMESTAMP_LTZ(9),
	PK_ID VARCHAR(16777216)
)
AS $$
    select t1.* exclude fsa_insert_date 
      from DEV.${FSA_CURRENT_SCHEMA}.open_po_all_historical t1
      join (
        select distinct insert_date,max(fsa_insert_date) over () fsa_insert_date
        from DEV.${FSA_CURRENT_SCHEMA}.open_po_all_historical
        where insert_date = 
          (select max(insert_date) insert_date
            from DEV.${FSA_CURRENT_SCHEMA}.open_po_all_historical
            where insert_date <= MAX_DATE)) t2
      on t1.insert_date = t2.insert_date
        and t1.fsa_insert_date = t2.fsa_insert_date
$$;

CREATE OR REPLACE FUNCTION DEV.${FSA_CURRENT_SCHEMA}.LATEST_OPEN_PO_ALL ()
  RETURNS TABLE (
	PO_ROW_NO NUMBER(18,0),
	PO_ITEM_ID FLOAT,
	PO_ITEM_TYPE VARCHAR(11),
	ITEM_ID FLOAT,
	ITEM VARCHAR(4400),
	ITEM_ID_C NUMBER(38,0),
	ITEM_C VARCHAR(4400),
	ITEM_DISPLAY_NAME VARCHAR(2000),
	ASSEMBLY_ITEM_ID FLOAT,
	ASSEMBLY_ITEM VARCHAR(4400),
	ASSEMBLY_ITEM_DISPLAY_NAME VARCHAR(2000),
	ORDER_NUMBER VARCHAR(360),
	PURCHASE_ORDER_TRANSACTION_ID FLOAT,
	STATUS VARCHAR(32000),
	LOCATION VARCHAR(480),
	RECEIVE_BY_DATE DATE,
	NS_RECEIVE_BY_DATE DATE,
	UNIQUE_KEY FLOAT,
	QUANTITY_TO_BE_RECEIVED FLOAT,
	HASH_VALUE VARCHAR(16777216),
	FSA_LOAD_STATUS VARCHAR(16777216),
	INSERT_DATE TIMESTAMP_LTZ(9),
	PK_ID VARCHAR(16777216)
)
AS $$
	select * from TABLE(DEV.${FSA_CURRENT_SCHEMA}.LATEST_OPEN_PO_ALL(current_timestamp()))
$$;

CREATE OR REPLACE PROCEDURE DEV.${FSA_CURRENT_SCHEMA}.MAKE_OPEN_PO_ALL(MAX_DATE timestamp_ltz,TARGET_TABLE text)
  RETURNS TABLE()
  LANGUAGE SQL
  EXECUTE AS CALLER
AS $$
  BEGIN
  LET rs RESULTSET := (CREATE OR REPLACE TABLE IDENTIFIER(:TARGET_TABLE) AS SELECT * FROM TABLE(DEV.${FSA_CURRENT_SCHEMA}.LATEST_OPEN_PO_ALL(:MAX_DATE)));
  return TABLE(rs);
  END;
$$;

CREATE OR REPLACE PROCEDURE DEV.${FSA_CURRENT_SCHEMA}.MAKE_OPEN_PO_ALL(MAX_DATE timestamp_ltz)
  RETURNS TABLE()
  LANGUAGE SQL
  EXECUTE AS CALLER
AS $$
  BEGIN
  LET rs RESULTSET := (CALL DEV.${FSA_CURRENT_SCHEMA}.MAKE_OPEN_PO_ALL(:MAX_DATE,'DEV.${FSA_CURRENT_SCHEMA}.OPEN_PO_ALL'));
  return TABLE(rs);
  END;
$$;

CREATE OR REPLACE PROCEDURE DEV.${FSA_CURRENT_SCHEMA}.MAKE_OPEN_PO_ALL()
  RETURNS TABLE()
  LANGUAGE SQL
  EXECUTE AS CALLER
AS $$
  BEGIN
  LET rs RESULTSET := (CALL DEV.${FSA_CURRENT_SCHEMA}.MAKE_OPEN_PO_ALL(current_timestamp()));
  return TABLE(rs);
  END;
$$;
