create or replace view FSA_CONSOLIDATED(
	ORDER_NUMBER,
	NS_LINE_NUMBER,
	TRANSACTION_ID,
	LINE_ID,
	FSA_OUTPUT_STATUS,
	CREATE_DATE,
	ROW_NO,
	ORIGINAL_CAPPING_DDA,
	FREDD,
	CAPPING_DDA
) as
SELECT ORDER_NUMBER
      ,NS_LINE_NUMBER
      ,TRANSACTION_ID
      ,LINE_ID
      ,FSA_OUTPUT_STATUS
      ,CREATE_DATE
      ,ROW_NO             AS "ROW_NO"
      ,ORIG_CAP_DDA       AS "ORIGINAL_CAPPING_DDA"
      ,MAX(FREDD)         AS "FREDD"
      ,MAX(CAPPING_DDA)   AS "CAPPING_DDA"
FROM DEV.NETSUITE2_SANDBOX_FSA.FSA
WHERE SOURCE_TYPE = 'OpenSO'
GROUP BY 1,2,3,4,5,6,7,8;
