create or replace view FSA_CONSOLIDATED(
	ORDER_NUMBER,
	NS_LINE_NUMBER,
	TRANSACTION_ID,
	LINE_ID,
	FSA_OUTPUT_STATUS,
	CREATE_DATE,
	ROW_NO,
	ORIGINAL_CAPPING_DDA,
	FREDD,
	CAPPING_DDA,
	SOURCE_TYPE,
	LOCATION
) as
SELECT ORDER_NUMBER
      ,NS_LINE_NUMBER
      ,TRANSACTION_ID
      ,LINE_ID
      ,FSA_OUTPUT_STATUS
      ,CREATE_DATE
      ,ROW_NO             AS "ROW_NO"
      ,ORIG_CAP_DDA       AS "ORIGINAL_CAPPING_DDA"
      ,FREDD              AS "FREDD"
      ,CAPPING_DDA        AS "CAPPING_DDA"
      ,SOURCE_TYPE
      ,LOCATION
FROM DEV.NETSUITE2_FSA.FSA
WHERE SOURCE_TYPE = 'OpenSO';