CREATE TABLE [dbo].[Demand_PO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FK_ID] [int] NULL,
	[OrderNumber] [varchar](50) NULL,
	[UNIQUE_KEY] [int] NULL,
	[DDA] [date] NULL,
	[DDA_Modified]  AS (case when [TRANS_TYPE]='Assembly' then [dbo].[AddBusinessDays]([DDA],(10)) else [DDA] end),
	[Org_DDA] [date] NULL,
	[Sequencing_DDA] [date] NULL,
	[TRANS_TYPE] [varchar](50) NULL,
	[TOTAL_AMT] [decimal](10, 2) NULL,
	[Priority_Level] [int] NULL,
	[NS_LINE_NUMBER] [int] NULL,
	[Item] [varchar](50) NULL,
	[ITEM_ID] [int] NULL,
	[COMPONENT_ITEM_ID] [int] NULL,
	[COMPONENT_ITEM] [varchar](50) NULL,
	[QUANTITY] [int] NULL,
	[TOTAL_AVAIL_QTY] [int] NULL,
	[COMPONENT_QTY_ORDERED] [int] NULL,
	[LOCATION] [varchar](50) NULL,
	[BO_STATUS] [varchar](10) NULL,
	[SourceType] [varchar](50) NULL,
	[SourceLoadDate_Prev] [date] NULL,
	[SourceLoadDate_Current] [date] NULL,
	[SourceType_Daily] [varchar](50) NULL,
	[PO_Splippage] [char](1) NULL,
	[InsertDate] [date] NOT NULL,
	[InsertDateTime] [datetime] NOT NULL)