CREATE OR REPLACE TABLE DEV.${FSA_CURRENT_SCHEMA}.DEMAND_PO AS
(
  SELECT distinct dpo.* EXCLUDE PK_ID,
  	"UNIQUE_KEY"||'^'||ZEROIFNULL("COMPONENT_ITEM_ID")::TEXT PK_ID,
  	prev.ROW_NO
  FROM DEV.${FSA_CURRENT_SCHEMA}.DEMAND_PO_ALL dpo
  LEFT OUTER JOIN (SELECT DISTINCT ORDER_NUMBER, ROW_NO FROM DEV.${FSA_CURRENT_SCHEMA}.DEMAND_PREV_ASSIGNED) prev
  	on dpo.ORDER_NUMBER = prev.ORDER_NUMBER
)
