CREATE TABLE IF NOT EXISTS DEV.${vj_fsa_schema}.DEMAND_PREV_ASSIGNED
	(PK_ID TEXT,
    /* 20230804 - KBY, RSF23-1861 - Convert ID's from FLOAT to NUMBER */
     UNIQUE_KEY NUMBER,
     COMPONENT_ITEM_ID NUMBER,
     ORDER_NUMBER TEXT,
     NS_LINE_NUMBER TEXT,
     HASH_VALUE NUMBER,
     HASH_FSA_OUTPUT NUMBER,
     INSERT_DATE TIMESTAMP_LTZ,
     LAST_MODIFIED TIMESTAMP_LTZ,
     ROW_NO NUMBER,
     PREV_AVAIL_DATE DATE,
     PREV_CAPPING_DDA DATE,
     ORIG_CAP_DDA DATE,
     PO_INDICATOR NUMBER,
     PO_INDICATOR_ASSIGN NUMBER,
     PO_ORDER_NUMBER TEXT,
     PO_RECEIVE_BY_DATE DATE,
  /* 20230728 - KBY, RSF23-2033 - Include global parameter FR_PREV_DAYS for adjustment */
     FR_PREV_DAYS NUMBER);
