create TABLE IF NOT EXISTS DEV.${vj_fsa_schema}.DEMAND_PREV_ASSIGNED_HISTORICAL (
	PK_ID VARCHAR(16777216),
    /* 20230728 - KBY, RSF23-1861 - Convert ID's from FLOAT to NUMBER */
	UNIQUE_KEY NUMBER,
	COMPONENT_ITEM_ID NUMBER,
	ORDER_NUMBER VARCHAR(16777216),
	NS_LINE_NUMBER VARCHAR(16777216),
	HASH_VALUE NUMBER(38,0),
	HASH_FSA_OUTPUT NUMBER(38,0),
	INSERT_DATE TIMESTAMP_LTZ(9),
	LAST_MODIFIED TIMESTAMP_LTZ(9),
	ROW_NO NUMBER(38,0),
	PREV_AVAIL_DATE DATE,
	PREV_CAPPING_DDA DATE,
	ORIG_CAP_DDA DATE,
	PO_INDICATOR NUMBER(38,0),
	PO_INDICATOR_ASSIGN NUMBER(38,0),
	PO_ORDER_NUMBER VARCHAR(16777216),
	PO_RECEIVE_BY_DATE DATE,
	/* 20230728 - KBY, RSF23-2033 - Include global parameter FR_PREV_DAYS for adjustment */
	FR_PREV_DAYS NUMBER,
	/* 20231128 - KBY, RSF23-3656 - Include NO_PO_DATE */ 
	NO_PO_DATE TIMESTAMP_LTZ,
	IS_VALID BOOLEAN DEFAULT TRUE,
	FSA_INSERT_DATE TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

/*
create or replace TABLE DEV.${vj_fsa_schema}.DEMAND_PREV_ASSIGNED_HISTORICAL_NEW
AS
    SELECT 
        PK_ID, 
        UNIQUE_KEY, 
        COMPONENT_ITEM_ID, 
        ORDER_NUMBER, 
        NS_LINE_NUMBER, 
        HASH_VALUE, 
        HASH_FSA_OUTPUT, 
        INSERT_DATE, 
        LAST_MODIFIED, 
        ROW_NO, 
        PREV_AVAIL_DATE, 
        PREV_CAPPING_DDA, 
        ORIG_CAP_DDA, 
        PO_INDICATOR, 
        PO_INDICATOR_ASSIGN, 
        PO_ORDER_NUMBER, 
        PO_RECEIVE_BY_DATE, 
        FR_PREV_DAYS,
        -- 20231128 - KBY, RSF23-3656 - Include NO_PO_DATE
        NULL:: TIMESTAMP_LTZ NO_PO_DATE,
        IS_VALID, 
        FSA_INSERT_DATE
    FROM DEV.${vj_fsa_schema}.DEMAND_PREV_ASSIGNED_HISTORICAL;
 */