INSERT INTO DEV.${FSA_PROD_SCHEMA}.DEMAND_PO_ALL_HISTORICAL
SELECT 
	* EXCLUDE QTY_ORDERED, 
    CURRENT_TIMESTAMP() AS FSA_INSERT_DATE,
    TRUE AS IS_VALID
FROM DEV.${FSA_PROD_SCHEMA}.DEMAND_PO_ALL;