INSERT INTO DEV.${vj_fsa_schema}.OPEN_PO_PREV_ASSIGNED_HISTORICAL
    SELECT 
        PK_ID, 
        HASH_VALUE, 
        INSERT_DATE, 
        LAST_MODIFIED, 
        TRUE IS_VALID, 
        CURRENT_TIMESTAMP() FSA_INSERT_DATE
FROM DEV.${vj_fsa_schema}.OPEN_PO_PREV_ASSIGNED;